language: php

php:
  - 5.6

cache:
  directories:
    - ~/.composer/cache/files

before_script:
  - composer post-clone
  - mysql -e 'create database smartcampus_test;'

script:
  - DB_CONNECTION=mysql DB_DATABASE=smartcampus_test DB_USERNAME=root DB_PASSWORD= vendor/bin/phpunit --debug